package com.sidvind.dbobject;

import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * @author David Sveningsson <david.sveningsson@bth.se>
 */
public interface DataLayer {
	public PreparedStatement prepareStatement(String sql) throws SQLException;
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException;
	
	/**
	 * Name of the selected database.
	 */
	public String dbname();
	
	/**
	 * Commit changes.
	 */
	public void commit();
	
	/**
	 * Rollback any changes.
	 */
	public void rollback();
}
